services:
  backend:
    build:
      context: ./GameServer
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://0.0.0.0:5000
    restart: unless-stopped

  frontend:
    build:
      context: ./GameClient
      dockerfile: Dockerfile
    volumes:
      - ./GameClient/customs:/usr/share/nginx/html/assets/custom
    depends_on:
      - backend
    restart: unless-stopped
